# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-14 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caldera', '0002_auto_20200214_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spesial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_spesial', to='caldera.Category'),
        ),
    ]
