# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-20 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-avatar.png', upload_to='profile_pics'),
        ),
    ]
